"""Framework-independent domain layer."""

from netsentinel.domain.connections import (
    ConnectionClosed,
    ConnectionClosureReason,
    ConnectionHistoryRecord,
    ConnectionKey,
    ConnectionLifecycleEvent,
    ConnectionOpened,
    ConnectionSnapshot,
    ConnectionState,
    ConnectionUpdated,
    Endpoint,
    ProcessIdentity,
    ProcessInfo,
    ProcessInfoStatus,
    TrackedConnection,
    TransportProtocol,
)
from netsentinel.domain.devices import NetworkContext, NetworkInterfaceKind
from netsentinel.domain.observations import (
    ArpObservation,
    ArpOpcode,
    LinkLayerProtocol,
    MacAddress,
    NetworkLayerProtocol,
    ObservationSource,
    PacketObservation,
)

__all__ = (
    "ArpObservation",
    "ArpOpcode",
    "ConnectionClosed",
    "ConnectionClosureReason",
    "ConnectionHistoryRecord",
    "ConnectionKey",
    "ConnectionLifecycleEvent",
    "ConnectionOpened",
    "ConnectionSnapshot",
    "ConnectionState",
    "ConnectionUpdated",
    "Endpoint",
    "LinkLayerProtocol",
    "MacAddress",
    "NetworkContext",
    "NetworkInterfaceKind",
    "NetworkLayerProtocol",
    "ObservationSource",
    "PacketObservation",
    "ProcessIdentity",
    "ProcessInfo",
    "ProcessInfoStatus",
    "TrackedConnection",
    "TransportProtocol",
)
