"""Reviewed enum display sources; persisted codes are unchanged."""
from enum import Enum
from netsentinel.shared.source_text import QT_TRANSLATE_NOOP

_SOURCES = {
    ('AlertStatus', 'open', 'raw'): QT_TRANSLATE_NOOP('AlertStatus.raw', 'open'),
    ('AlertStatus', 'open', 'title'): QT_TRANSLATE_NOOP('AlertStatus.title', 'Open'),
    ('AlertStatus', 'acknowledged', 'raw'): QT_TRANSLATE_NOOP('AlertStatus.raw', 'acknowledged'),
    ('AlertStatus', 'acknowledged', 'title'): QT_TRANSLATE_NOOP('AlertStatus.title', 'Acknowledged'),
    ('AlertStatus', 'resolved', 'raw'): QT_TRANSLATE_NOOP('AlertStatus.raw', 'resolved'),
    ('AlertStatus', 'resolved', 'title'): QT_TRANSLATE_NOOP('AlertStatus.title', 'Resolved'),
    ('ApplicationIdentityQuality', 'stable', 'raw'): QT_TRANSLATE_NOOP('ApplicationIdentityQuality.raw', 'stable'),
    ('ApplicationIdentityQuality', 'stable', 'human'): QT_TRANSLATE_NOOP('ApplicationIdentityQuality.human', 'Stable'),
    ('ApplicationIdentityQuality', 'provisional', 'raw'): QT_TRANSLATE_NOOP('ApplicationIdentityQuality.raw', 'provisional'),
    ('ApplicationIdentityQuality', 'provisional', 'human'): QT_TRANSLATE_NOOP('ApplicationIdentityQuality.human', 'Provisional'),
    ('ApplicationIdentityQuality', 'unknown', 'raw'): QT_TRANSLATE_NOOP('ApplicationIdentityQuality.raw', 'unknown'),
    ('ApplicationIdentityQuality', 'unknown', 'human'): QT_TRANSLATE_NOOP('ApplicationIdentityQuality.human', 'Unknown'),
    ('BaselineState', 'learning', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'LEARNING'),
    ('BaselineState', 'insufficient_data', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'INSUFFICIENT_DATA'),
    ('BaselineState', 'insufficient_quality', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'INSUFFICIENT_QUALITY'),
    ('BaselineState', 'ready', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'READY'),
    ('BaselineState', 'stale', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'STALE'),
    ('BaselineState', 'expired', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'EXPIRED'),
    ('BaselineState', 'clock_anomaly', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'CLOCK_ANOMALY'),
    ('BaselineState', 'corrupt', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'CORRUPT'),
    ('BaselineState', 'unsupported_version', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'UNSUPPORTED_VERSION'),
    ('BaselineState', 'policy_mismatch', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'POLICY_MISMATCH'),
    ('BaselineState', 'unavailable', 'upper'): QT_TRANSLATE_NOOP('BaselineState.upper', 'UNAVAILABLE'),
    ('BaselineOrigin', 'new', 'raw'): QT_TRANSLATE_NOOP('BaselineOrigin.raw', 'new'),
    ('BaselineOrigin', 'restored', 'raw'): QT_TRANSLATE_NOOP('BaselineOrigin.raw', 'restored'),
    ('BaselineOrigin', 'reset', 'raw'): QT_TRANSLATE_NOOP('BaselineOrigin.raw', 'reset'),
    ('BaselineOrigin', 'previous_unavailable', 'raw'): QT_TRANSLATE_NOOP('BaselineOrigin.raw', 'previous_unavailable'),
    ('BaselineOrigin', 'session_only', 'raw'): QT_TRANSLATE_NOOP('BaselineOrigin.raw', 'session_only'),
    ('BaselineStorageState', 'loading', 'raw'): QT_TRANSLATE_NOOP('BaselineStorageState.raw', 'loading'),
    ('BaselineStorageState', 'available', 'raw'): QT_TRANSLATE_NOOP('BaselineStorageState.raw', 'available'),
    ('BaselineStorageState', 'unavailable', 'raw'): QT_TRANSLATE_NOOP('BaselineStorageState.raw', 'unavailable'),
    ('ConnectionState', 'none', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'None'),
    ('ConnectionState', 'listen', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Listen'),
    ('ConnectionState', 'established', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Established'),
    ('ConnectionState', 'syn_sent', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Syn Sent'),
    ('ConnectionState', 'syn_received', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Syn Received'),
    ('ConnectionState', 'fin_wait_1', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Fin Wait 1'),
    ('ConnectionState', 'fin_wait_2', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Fin Wait 2'),
    ('ConnectionState', 'close_wait', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Close Wait'),
    ('ConnectionState', 'closing', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Closing'),
    ('ConnectionState', 'last_ack', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Last Ack'),
    ('ConnectionState', 'time_wait', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Time Wait'),
    ('ConnectionState', 'closed', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Closed'),
    ('ConnectionState', 'unknown', 'title'): QT_TRANSLATE_NOOP('ConnectionState.title', 'Unknown'),
    ('ObservationQuality', 'complete', 'human'): QT_TRANSLATE_NOOP('ObservationQuality.human', 'Complete'),
    ('ObservationQuality', 'complete', 'raw'): QT_TRANSLATE_NOOP('ObservationQuality.raw', 'complete'),
    ('ObservationQuality', 'reduced', 'human'): QT_TRANSLATE_NOOP('ObservationQuality.human', 'Reduced'),
    ('ObservationQuality', 'reduced', 'raw'): QT_TRANSLATE_NOOP('ObservationQuality.raw', 'reduced'),
    ('ObservationQuality', 'failed', 'human'): QT_TRANSLATE_NOOP('ObservationQuality.human', 'Failed'),
    ('ObservationQuality', 'failed', 'raw'): QT_TRANSLATE_NOOP('ObservationQuality.raw', 'failed'),
    ('NetworkScopeStatus', 'resolved', 'raw'): QT_TRANSLATE_NOOP('NetworkScopeStatus.raw', 'resolved'),
    ('NetworkScopeStatus', 'resolved', 'words'): QT_TRANSLATE_NOOP('NetworkScopeStatus.words', 'resolved'),
    ('NetworkScopeStatus', 'resolved', 'human'): QT_TRANSLATE_NOOP('NetworkScopeStatus.human', 'Resolved'),
    ('NetworkScopeStatus', 'unknown', 'raw'): QT_TRANSLATE_NOOP('NetworkScopeStatus.raw', 'unknown'),
    ('NetworkScopeStatus', 'unknown', 'words'): QT_TRANSLATE_NOOP('NetworkScopeStatus.words', 'unknown'),
    ('NetworkScopeStatus', 'unknown', 'human'): QT_TRANSLATE_NOOP('NetworkScopeStatus.human', 'Unknown'),
    ('NetworkScopeStatus', 'ambiguous', 'raw'): QT_TRANSLATE_NOOP('NetworkScopeStatus.raw', 'ambiguous'),
    ('NetworkScopeStatus', 'ambiguous', 'words'): QT_TRANSLATE_NOOP('NetworkScopeStatus.words', 'ambiguous'),
    ('NetworkScopeStatus', 'ambiguous', 'human'): QT_TRANSLATE_NOOP('NetworkScopeStatus.human', 'Ambiguous'),
    ('DestinationNoveltyClassification', 'known', 'upper'): QT_TRANSLATE_NOOP('DestinationNoveltyClassification.upper', 'KNOWN'),
    ('DestinationNoveltyClassification', 'rare', 'upper'): QT_TRANSLATE_NOOP('DestinationNoveltyClassification.upper', 'RARE'),
    ('DestinationNoveltyClassification', 'first_seen', 'upper'): QT_TRANSLATE_NOOP('DestinationNoveltyClassification.upper', 'FIRST_SEEN'),
    ('DestinationNoveltyClassification', 'insufficient_data', 'upper'): QT_TRANSLATE_NOOP('DestinationNoveltyClassification.upper', 'INSUFFICIENT_DATA'),
    ('DestinationNoveltyClassification', 'insufficient_quality', 'upper'): QT_TRANSLATE_NOOP('DestinationNoveltyClassification.upper', 'INSUFFICIENT_QUALITY'),
    ('DestinationNoveltyClassification', 'not_evaluated', 'upper'): QT_TRANSLATE_NOOP('DestinationNoveltyClassification.upper', 'NOT_EVALUATED'),
    ('DestinationNoveltyReason', 'destination_established', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'destination established'),
    ('DestinationNoveltyReason', 'destination_rarely_observed', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'destination rarely observed'),
    ('DestinationNoveltyReason', 'destination_not_previously_observed', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'destination not previously observed'),
    ('DestinationNoveltyReason', 'initial_observation', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'initial observation'),
    ('DestinationNoveltyReason', 'failed_round', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'failed round'),
    ('DestinationNoveltyReason', 'remote_unavailable', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'remote unavailable'),
    ('DestinationNoveltyReason', 'application_scope_unavailable', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'application scope unavailable'),
    ('DestinationNoveltyReason', 'network_scope_unavailable', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'network scope unavailable'),
    ('DestinationNoveltyReason', 'application_scope_mismatch', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'application scope mismatch'),
    ('DestinationNoveltyReason', 'revision_mismatch', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'revision mismatch'),
    ('DestinationNoveltyReason', 'network_scope_mismatch', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'network scope mismatch'),
    ('DestinationNoveltyReason', 'baseline_learning', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline learning'),
    ('DestinationNoveltyReason', 'baseline_insufficient_data', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline insufficient data'),
    ('DestinationNoveltyReason', 'baseline_insufficient_quality', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline insufficient quality'),
    ('DestinationNoveltyReason', 'baseline_stale', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline stale'),
    ('DestinationNoveltyReason', 'baseline_expired', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline expired'),
    ('DestinationNoveltyReason', 'baseline_clock_anomaly', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline clock anomaly'),
    ('DestinationNoveltyReason', 'baseline_corrupt', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline corrupt'),
    ('DestinationNoveltyReason', 'baseline_unsupported_version', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline unsupported version'),
    ('DestinationNoveltyReason', 'baseline_policy_mismatch', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline policy mismatch'),
    ('DestinationNoveltyReason', 'baseline_unavailable', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'baseline unavailable'),
    ('DestinationNoveltyReason', 'history_incomplete', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'history incomplete'),
    ('DestinationNoveltyReason', 'destination_overflow', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'destination overflow'),
    ('DestinationNoveltyReason', 'capacity_loss', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'capacity loss'),
    ('DestinationNoveltyReason', 'counter_saturated', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'counter saturated'),
    ('DestinationNoveltyReason', 'minimum_samples', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'minimum samples'),
    ('DestinationNoveltyReason', 'minimum_monitored_duration', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'minimum monitored duration'),
    ('DestinationNoveltyReason', 'rarity_minimum_samples', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyReason.words', 'rarity minimum samples'),
    ('DestinationNoveltyLimitation', 'ip_only_service_not_inferred', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyLimitation.words', 'ip only service not inferred'),
    ('DestinationNoveltyLimitation', 'revision_unverified', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyLimitation.words', 'revision unverified'),
    ('DestinationNoveltyLimitation', 'reduced_current_observation', 'words'): QT_TRANSLATE_NOOP('DestinationNoveltyLimitation.words', 'reduced current observation'),
    ('DeviceTrust', 'unknown', 'raw'): QT_TRANSLATE_NOOP('DeviceTrust.raw', 'unknown'),
    ('DeviceTrust', 'unknown', 'title'): QT_TRANSLATE_NOOP('DeviceTrust.title', 'Unknown'),
    ('DeviceTrust', 'trusted', 'raw'): QT_TRANSLATE_NOOP('DeviceTrust.raw', 'trusted'),
    ('DeviceTrust', 'trusted', 'title'): QT_TRANSLATE_NOOP('DeviceTrust.title', 'Trusted'),
    ('DeviceTrust', 'untrusted', 'raw'): QT_TRANSLATE_NOOP('DeviceTrust.raw', 'untrusted'),
    ('DeviceTrust', 'untrusted', 'title'): QT_TRANSLATE_NOOP('DeviceTrust.title', 'Untrusted'),
    ('SignatureKind', 'embedded', 'raw'): QT_TRANSLATE_NOOP('SignatureKind.raw', 'embedded'),
    ('SignatureKind', 'catalog', 'raw'): QT_TRANSLATE_NOOP('SignatureKind.raw', 'catalog'),
    ('SignatureKind', 'none', 'raw'): QT_TRANSLATE_NOOP('SignatureKind.raw', 'none'),
    ('SignatureKind', 'unknown', 'raw'): QT_TRANSLATE_NOOP('SignatureKind.raw', 'unknown'),
    ('SignatureValidation', 'valid', 'words'): QT_TRANSLATE_NOOP('SignatureValidation.words', 'valid'),
    ('SignatureValidation', 'invalid', 'words'): QT_TRANSLATE_NOOP('SignatureValidation.words', 'invalid'),
    ('SignatureValidation', 'not_signed', 'words'): QT_TRANSLATE_NOOP('SignatureValidation.words', 'not signed'),
    ('SignatureValidation', 'unknown', 'words'): QT_TRANSLATE_NOOP('SignatureValidation.words', 'unknown'),
    ('LocalTrust', 'trusted_local_policy', 'words'): QT_TRANSLATE_NOOP('LocalTrust.words', 'trusted local policy'),
    ('LocalTrust', 'untrusted', 'words'): QT_TRANSLATE_NOOP('LocalTrust.words', 'untrusted'),
    ('LocalTrust', 'unknown', 'words'): QT_TRANSLATE_NOOP('LocalTrust.words', 'unknown'),
    ('LocalTrust', 'not_evaluated', 'words'): QT_TRANSLATE_NOOP('LocalTrust.words', 'not evaluated'),
    ('RevocationStatus', 'not_checked', 'words'): QT_TRANSLATE_NOOP('RevocationStatus.words', 'not checked'),
    ('SignerAvailability', 'available', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'available'),
    ('SignerAvailability', 'not_found', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'not found'),
    ('SignerAvailability', 'access_denied', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'access denied'),
    ('SignerAvailability', 'invalid_path', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'invalid path'),
    ('SignerAvailability', 'remote_path', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'remote path'),
    ('SignerAvailability', 'unsupported', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'unsupported'),
    ('SignerAvailability', 'file_changed', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'file changed'),
    ('SignerAvailability', 'too_large', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'too large'),
    ('SignerAvailability', 'unavailable', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'unavailable'),
    ('SignerAvailability', 'saturated', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'saturated'),
    ('SignerAvailability', 'cancelled', 'words'): QT_TRANSLATE_NOOP('SignerAvailability.words', 'cancelled'),
    ('BehaviorClassification', 'normal', 'upper'): QT_TRANSLATE_NOOP('BehaviorClassification.upper', 'NORMAL'),
    ('BehaviorClassification', 'elevated_unconfirmed', 'upper'): QT_TRANSLATE_NOOP('BehaviorClassification.upper', 'ELEVATED_UNCONFIRMED'),
    ('BehaviorClassification', 'elevated_confirmed', 'upper'): QT_TRANSLATE_NOOP('BehaviorClassification.upper', 'ELEVATED_CONFIRMED'),
    ('BehaviorClassification', 'insufficient_data', 'upper'): QT_TRANSLATE_NOOP('BehaviorClassification.upper', 'INSUFFICIENT_DATA'),
    ('BehaviorClassification', 'insufficient_quality', 'upper'): QT_TRANSLATE_NOOP('BehaviorClassification.upper', 'INSUFFICIENT_QUALITY'),
    ('BehaviorClassification', 'not_evaluated', 'upper'): QT_TRANSLATE_NOOP('BehaviorClassification.upper', 'NOT_EVALUATED'),
    ('BehaviorReason', 'within_expected_range', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'within expected range'),
    ('BehaviorReason', 'appearance_rate_elevated', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'appearance rate elevated'),
    ('BehaviorReason', 'destination_diversity_elevated', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'destination diversity elevated'),
    ('BehaviorReason', 'baseline_not_ready', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'baseline not ready'),
    ('BehaviorReason', 'baseline_unavailable', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'baseline unavailable'),
    ('BehaviorReason', 'baseline_invalid', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'baseline invalid'),
    ('BehaviorReason', 'policy_mismatch', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'policy mismatch'),
    ('BehaviorReason', 'scope_unavailable', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'scope unavailable'),
    ('BehaviorReason', 'scope_mismatch', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'scope mismatch'),
    ('BehaviorReason', 'current_window_too_short', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'current window too short'),
    ('BehaviorReason', 'current_sample_too_small', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'current sample too small'),
    ('BehaviorReason', 'current_invalid', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'current invalid'),
    ('BehaviorReason', 'quality_insufficient', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'quality insufficient'),
    ('BehaviorReason', 'capacity_limited', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'capacity limited'),
    ('BehaviorReason', 'reference_too_small', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'reference too small'),
    ('BehaviorReason', 'reference_not_comparable', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'reference not comparable'),
    ('BehaviorReason', 'cooldown_active', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'cooldown active'),
    ('BehaviorReason', 'window_not_independent', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'window not independent'),
    ('BehaviorReason', 'clock_anomaly', 'words'): QT_TRANSLATE_NOOP('BehaviorReason.words', 'clock anomaly'),
    ('IncidentLimitation', 'quality_limited', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'quality limited'),
    ('IncidentLimitation', 'monitoring_gap', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'monitoring gap'),
    ('IncidentLimitation', 'canonical_reference_across_gap', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'canonical reference across gap'),
    ('IncidentLimitation', 'multiple_matching_incidents_not_unioned', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'multiple matching incidents not unioned'),
    ('IncidentLimitation', 'capacity_limited', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'capacity limited'),
    ('IncidentLimitation', 'gap_marker_capacity_continuity_unknown', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'gap marker capacity continuity unknown'),
    ('IncidentLimitation', 'outside_supported_lateness', 'words'): QT_TRANSLATE_NOOP('IncidentLimitation.words', 'outside supported lateness'),
    ('IncidentState', 'open', 'raw'): QT_TRANSLATE_NOOP('IncidentState.raw', 'open'),
    ('IncidentState', 'acknowledged', 'raw'): QT_TRANSLATE_NOOP('IncidentState.raw', 'acknowledged'),
    ('IncidentState', 'resolved', 'raw'): QT_TRANSLATE_NOOP('IncidentState.raw', 'resolved'),
    ('IncidentAction', 'created', 'raw'): QT_TRANSLATE_NOOP('IncidentAction.raw', 'created'),
    ('IncidentAction', 'appended', 'raw'): QT_TRANSLATE_NOOP('IncidentAction.raw', 'appended'),
    ('IncidentAction', 'acknowledged', 'raw'): QT_TRANSLATE_NOOP('IncidentAction.raw', 'acknowledged'),
    ('IncidentAction', 'resolved', 'raw'): QT_TRANSLATE_NOOP('IncidentAction.raw', 'resolved'),
    ('IncidentAction', 'reopened', 'raw'): QT_TRANSLATE_NOOP('IncidentAction.raw', 'reopened'),
    ('IncidentOrigin', 'manual_user', 'raw'): QT_TRANSLATE_NOOP('IncidentOrigin.raw', 'manual_user'),
    ('IncidentOrigin', 'system_correlation', 'raw'): QT_TRANSLATE_NOOP('IncidentOrigin.raw', 'system_correlation'),
    ('IncidentStatus', 'found', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'found'),
    ('IncidentStatus', 'changed', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'changed'),
    ('IncidentStatus', 'no_change', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'no_change'),
    ('IncidentStatus', 'not_found', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'not_found'),
    ('IncidentStatus', 'conflict', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'conflict'),
    ('IncidentStatus', 'identity_conflict', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'identity_conflict'),
    ('IncidentStatus', 'invalid_transition', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'invalid_transition'),
    ('IncidentStatus', 'not_correlated', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'not_correlated'),
    ('IncidentStatus', 'horizon_exceeded', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'horizon_exceeded'),
    ('IncidentStatus', 'capacity_reached', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'capacity_reached'),
    ('IncidentStatus', 'corrupt', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'corrupt'),
    ('IncidentStatus', 'unsupported_version', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'unsupported_version'),
    ('IncidentStatus', 'unavailable', 'raw'): QT_TRANSLATE_NOOP('IncidentStatus.raw', 'unavailable'),
    ('PeriodicityClassification', 'insufficient_data', 'upper'): QT_TRANSLATE_NOOP('PeriodicityClassification.upper', 'INSUFFICIENT_DATA'),
    ('PeriodicityClassification', 'irregular', 'upper'): QT_TRANSLATE_NOOP('PeriodicityClassification.upper', 'IRREGULAR'),
    ('PeriodicityClassification', 'periodic_candidate', 'upper'): QT_TRANSLATE_NOOP('PeriodicityClassification.upper', 'PERIODIC_CANDIDATE'),
    ('PeriodicityClassification', 'resolution_limited', 'upper'): QT_TRANSLATE_NOOP('PeriodicityClassification.upper', 'RESOLUTION_LIMITED'),
    ('PeriodicityReason', 'minimum_intervals', 'words'): QT_TRANSLATE_NOOP('PeriodicityReason.words', 'minimum intervals'),
    ('PeriodicityReason', 'jitter_exceeded', 'words'): QT_TRANSLATE_NOOP('PeriodicityReason.words', 'jitter exceeded'),
    ('PeriodicityReason', 'period_out_of_range', 'words'): QT_TRANSLATE_NOOP('PeriodicityReason.words', 'period out of range'),
    ('PeriodicityReason', 'observation_resolution', 'words'): QT_TRANSLATE_NOOP('PeriodicityReason.words', 'observation resolution'),
    ('PeriodicityReason', 'intervals_regular', 'words'): QT_TRANSLATE_NOOP('PeriodicityReason.words', 'intervals regular'),
    ('PeriodicityReason', 'multiples_compatible', 'words'): QT_TRANSLATE_NOOP('PeriodicityReason.words', 'multiples compatible'),
    ('PeriodicityLimitation', 'polling_quantized_exact_timer_not_inferred', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'polling quantized exact timer not inferred'),
    ('PeriodicityLimitation', 'benign_updates_telemetry_sync_reconnects_compatible', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'benign updates telemetry sync reconnects compatible'),
    ('PeriodicityLimitation', 'behavioral_only_low_security_significance', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'behavioral only low security significance'),
    ('PeriodicityLimitation', 'revision_unverified', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'revision unverified'),
    ('PeriodicityLimitation', 'missed_multiple_compatible_not_proven', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'missed multiple compatible not proven'),
    ('PeriodicityLimitation', 'recent_bounded_sequence_only', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'recent bounded sequence only'),
    ('PeriodicityLimitation', 'prior_history_unavailable', 'words'): QT_TRANSLATE_NOOP('PeriodicityLimitation.words', 'prior history unavailable'),
    ('PreferenceEffect', 'notification_suppression', 'human'): QT_TRANSLATE_NOOP('PreferenceEffect.human', 'Notification suppression'),
    ('PreferenceStatus', 'active', 'human'): QT_TRANSLATE_NOOP('PreferenceStatus.human', 'Active'),
    ('PreferenceStatus', 'active', 'upper'): QT_TRANSLATE_NOOP('PreferenceStatus.upper', 'ACTIVE'),
    ('PreferenceStatus', 'revoked', 'human'): QT_TRANSLATE_NOOP('PreferenceStatus.human', 'Revoked'),
    ('PreferenceStatus', 'revoked', 'upper'): QT_TRANSLATE_NOOP('PreferenceStatus.upper', 'REVOKED'),
    ('PreferenceStatus', 'expired', 'human'): QT_TRANSLATE_NOOP('PreferenceStatus.human', 'Expired'),
    ('PreferenceStatus', 'expired', 'upper'): QT_TRANSLATE_NOOP('PreferenceStatus.upper', 'EXPIRED'),
    ('ResponseProfile', 'domain', 'title'): QT_TRANSLATE_NOOP('ResponseProfile.title', 'Domain'),
    ('ResponseProfile', 'private', 'title'): QT_TRANSLATE_NOOP('ResponseProfile.title', 'Private'),
    ('ResponseProfile', 'public', 'title'): QT_TRANSLATE_NOOP('ResponseProfile.title', 'Public'),
    ('ResponseSourceStatus', 'available', 'raw'): QT_TRANSLATE_NOOP('ResponseSourceStatus.raw', 'available'),
    ('ResponseSourceStatus', 'expired', 'raw'): QT_TRANSLATE_NOOP('ResponseSourceStatus.raw', 'expired'),
    ('ResponseSourceStatus', 'unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseSourceStatus.raw', 'unavailable'),
    ('ResponseAction', 'create', 'raw'): QT_TRANSLATE_NOOP('ResponseAction.raw', 'create'),
    ('ResponseAction', 'create', 'upper'): QT_TRANSLATE_NOOP('ResponseAction.upper', 'CREATE'),
    ('ResponseAction', 'remove', 'raw'): QT_TRANSLATE_NOOP('ResponseAction.raw', 'remove'),
    ('ResponseAction', 'remove', 'upper'): QT_TRANSLATE_NOOP('ResponseAction.upper', 'REMOVE'),
    ('ResponseOutcome', 'not_attempted', 'raw'): QT_TRANSLATE_NOOP('ResponseOutcome.raw', 'not_attempted'),
    ('ResponseOutcome', 'failed', 'raw'): QT_TRANSLATE_NOOP('ResponseOutcome.raw', 'failed'),
    ('ResponseOutcome', 'outcome_unknown', 'raw'): QT_TRANSLATE_NOOP('ResponseOutcome.raw', 'outcome_unknown'),
    ('ResponseOutcome', 'partial', 'raw'): QT_TRANSLATE_NOOP('ResponseOutcome.raw', 'partial'),
    ('ResponseOutcome', 'verified', 'raw'): QT_TRANSLATE_NOOP('ResponseOutcome.raw', 'verified'),
    ('ResponseRuleState', 'unknown', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'unknown'),
    ('ResponseRuleState', 'present_enabled', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'present_enabled'),
    ('ResponseRuleState', 'absent', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'absent'),
    ('ResponseRuleState', 'inactive_profile', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'inactive_profile'),
    ('ResponseRuleState', 'externally_disabled', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'externally_disabled'),
    ('ResponseRuleState', 'externally_modified', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'externally_modified'),
    ('ResponseRuleState', 'externally_missing', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'externally_missing'),
    ('ResponseRuleState', 'ownership_conflict', 'raw'): QT_TRANSLATE_NOOP('ResponseRuleState.raw', 'ownership_conflict'),
    ('ResponseReason', 'boundary_unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'boundary_unavailable'),
    ('ResponseReason', 'privilege_required', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'privilege_required'),
    ('ResponseReason', 'access_denied', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'access_denied'),
    ('ResponseReason', 'uac_cancelled', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'uac_cancelled'),
    ('ResponseReason', 'read_unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'read_unavailable'),
    ('ResponseReason', 'policy_limited', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'policy_limited'),
    ('ResponseReason', 'revalidation_required', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'revalidation_required'),
    ('ResponseReason', 'confirmation_required', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'confirmation_required'),
    ('ResponseReason', 'stale_confirmation', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'stale_confirmation'),
    ('ResponseReason', 'target_unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'target_unavailable'),
    ('ResponseReason', 'ownership_conflict', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'ownership_conflict'),
    ('ResponseReason', 'storage_unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'storage_unavailable'),
    ('ResponseReason', 'readback_unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'readback_unavailable'),
    ('ResponseReason', 'os_db_disagreement', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'os_db_disagreement'),
    ('ResponseReason', 'rule_readback_verified', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'rule_readback_verified'),
    ('ResponseReason', 'invalid_request', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'invalid_request'),
    ('ResponseReason', 'unsupported', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'unsupported'),
    ('ResponseReason', 'backend_unavailable', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'backend_unavailable'),
    ('ResponseReason', 'operation_failed', 'raw'): QT_TRANSLATE_NOOP('ResponseReason.raw', 'operation_failed'),
    ('ResponseOperationStatus', 'prepared', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'prepared'),
    ('ResponseOperationStatus', 'attempt', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'attempt'),
    ('ResponseOperationStatus', 'os_verified', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'os_verified'),
    ('ResponseOperationStatus', 'verified', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'verified'),
    ('ResponseOperationStatus', 'failure', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'failure'),
    ('ResponseOperationStatus', 'unknown', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'unknown'),
    ('ResponseOperationStatus', 'partial', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'partial'),
    ('ResponseOperationStatus', 'not_materialized', 'raw'): QT_TRANSLATE_NOOP('ResponseOperationStatus.raw', 'not_materialized'),
    ('ResponseReconciliation', 'pending_create', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'pending_create'),
    ('ResponseReconciliation', 'pending_remove', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'pending_remove'),
    ('ResponseReconciliation', 'exact', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'exact'),
    ('ResponseReconciliation', 'promoted', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'promoted'),
    ('ResponseReconciliation', 'not_materialized', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'not_materialized'),
    ('ResponseReconciliation', 'external_missing', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'external_missing'),
    ('ResponseReconciliation', 'external_modified', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'external_modified'),
    ('ResponseReconciliation', 'externally_disabled', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'externally_disabled'),
    ('ResponseReconciliation', 'ambiguous', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'ambiguous'),
    ('ResponseReconciliation', 'unknown', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'unknown'),
    ('ResponseReconciliation', 'removed', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'removed'),
    ('ResponseReconciliation', 'absence_observed', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'absence_observed'),
    ('ResponseReconciliation', 'expired', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'expired'),
    ('ResponseReconciliation', 'expiry_pending', 'raw'): QT_TRANSLATE_NOOP('ResponseReconciliation.raw', 'expiry_pending'),
    ('ResponseAuditEvent', 'prepared', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'prepared'),
    ('ResponseAuditEvent', 'attempt', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'attempt'),
    ('ResponseAuditEvent', 'readback_verified', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'readback_verified'),
    ('ResponseAuditEvent', 'verified_success', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'verified_success'),
    ('ResponseAuditEvent', 'failure', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'failure'),
    ('ResponseAuditEvent', 'unknown_partial', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'unknown_partial'),
    ('ResponseAuditEvent', 'recovery_promotion', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'recovery_promotion'),
    ('ResponseAuditEvent', 'recovery', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'recovery'),
    ('ResponseAuditEvent', 'rollback_attempt', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'rollback_attempt'),
    ('ResponseAuditEvent', 'rollback_success', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'rollback_success'),
    ('ResponseAuditEvent', 'rollback_failure', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'rollback_failure'),
    ('ResponseAuditEvent', 'external_drift', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'external_drift'),
    ('ResponseAuditEvent', 'external_missing', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'external_missing'),
    ('ResponseAuditEvent', 'expiry_pending', 'raw'): QT_TRANSLATE_NOOP('ResponseAuditEvent.raw', 'expiry_pending'),
    ('AssessmentReadStatus', 'found', 'human'): QT_TRANSLATE_NOOP('AssessmentReadStatus.human', 'Found'),
    ('AssessmentReadStatus', 'not_found', 'human'): QT_TRANSLATE_NOOP('AssessmentReadStatus.human', 'Not found'),
    ('AssessmentReadStatus', 'corrupt', 'human'): QT_TRANSLATE_NOOP('AssessmentReadStatus.human', 'Corrupt'),
    ('AssessmentReadStatus', 'unsupported_version', 'human'): QT_TRANSLATE_NOOP('AssessmentReadStatus.human', 'Unsupported version'),
    ('AssessmentReadStatus', 'unavailable', 'human'): QT_TRANSLATE_NOOP('AssessmentReadStatus.human', 'Unavailable'),
    ('AssessmentSourceStatus', 'available', 'human'): QT_TRANSLATE_NOOP('AssessmentSourceStatus.human', 'Available'),
    ('AssessmentSourceStatus', 'source_expired_or_unavailable', 'human'): QT_TRANSLATE_NOOP('AssessmentSourceStatus.human', 'Source expired or unavailable'),
    ('AssessmentSourceStatus', 'unresolved', 'human'): QT_TRANSLATE_NOOP('AssessmentSourceStatus.human', 'Unresolved'),
    ('EvidenceSource', 'threat_intelligence', 'human'): QT_TRANSLATE_NOOP('EvidenceSource.human', 'Threat intelligence'),
    ('EvidenceSource', 'arp_identity', 'human'): QT_TRANSLATE_NOOP('EvidenceSource.human', 'Arp identity'),
    ('EvidenceSource', 'destination_novelty', 'human'): QT_TRANSLATE_NOOP('EvidenceSource.human', 'Destination novelty'),
    ('EvidenceSource', 'frequency_diversity', 'human'): QT_TRANSLATE_NOOP('EvidenceSource.human', 'Frequency diversity'),
    ('EvidenceSource', 'periodicity', 'human'): QT_TRANSLATE_NOOP('EvidenceSource.human', 'Periodicity'),
    ('EvidenceRole', 'observation', 'human'): QT_TRANSLATE_NOOP('EvidenceRole.human', 'Observation'),
    ('EvidenceRole', 'finding', 'human'): QT_TRANSLATE_NOOP('EvidenceRole.human', 'Finding'),
    ('EvidenceRole', 'limitation', 'human'): QT_TRANSLATE_NOOP('EvidenceRole.human', 'Limitation'),
    ('EvidenceConfidence', 'passive_observation', 'human'): QT_TRANSLATE_NOOP('EvidenceConfidence.human', 'Passive observation'),
    ('EvidenceConfidence', 'low', 'human'): QT_TRANSLATE_NOOP('EvidenceConfidence.human', 'Low'),
    ('EvidenceConfidence', 'moderate', 'human'): QT_TRANSLATE_NOOP('EvidenceConfidence.human', 'Moderate'),
    ('EvidenceConfidence', 'high', 'human'): QT_TRANSLATE_NOOP('EvidenceConfidence.human', 'High'),
    ('Freshness', 'current', 'human'): QT_TRANSLATE_NOOP('Freshness.human', 'Current'),
    ('Freshness', 'stale', 'human'): QT_TRANSLATE_NOOP('Freshness.human', 'Stale'),
    ('Freshness', 'expired', 'human'): QT_TRANSLATE_NOOP('Freshness.human', 'Expired'),
    ('Freshness', 'unknown', 'human'): QT_TRANSLATE_NOOP('Freshness.human', 'Unknown'),
    ('ContributorFamily', 'novelty', 'human'): QT_TRANSLATE_NOOP('ContributorFamily.human', 'Novelty'),
    ('ContributorFamily', 'frequency', 'human'): QT_TRANSLATE_NOOP('ContributorFamily.human', 'Frequency'),
    ('ContributorFamily', 'diversity', 'human'): QT_TRANSLATE_NOOP('ContributorFamily.human', 'Diversity'),
    ('ContributorFamily', 'periodicity', 'human'): QT_TRANSLATE_NOOP('ContributorFamily.human', 'Periodicity'),
    ('ContributorFamily', 'identity', 'human'): QT_TRANSLATE_NOOP('ContributorFamily.human', 'Identity'),
    ('ContributorFamily', 'schedule_compatibility', 'human'): QT_TRANSLATE_NOOP('ContributorFamily.human', 'Schedule compatibility'),
    ('ScoringReason', 'rule_applied', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Rule applied'),
    ('ScoringReason', 'observation_only', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Observation only'),
    ('ScoringReason', 'schedule_compatible_not_verified_benign', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Schedule compatible not verified benign'),
    ('ScoringReason', 'unknown_freshness', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Unknown freshness'),
    ('ScoringReason', 'stale', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Stale'),
    ('ScoringReason', 'expired', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Expired'),
    ('ScoringReason', 'unsupported_rule', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Unsupported rule'),
    ('ScoringReason', 'unsupported_producer_version', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Unsupported producer version'),
    ('ScoringReason', 'legacy_context_required', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Legacy context required'),
    ('ScoringReason', 'limitation_only', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Limitation only'),
    ('ScoringReason', 'insufficient_data', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Insufficient data'),
    ('ScoringReason', 'insufficient_quality', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Insufficient quality'),
    ('ScoringReason', 'not_evaluated', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Not evaluated'),
    ('ScoringReason', 'resolution_limited', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Resolution limited'),
    ('ScoringReason', 'role_mismatch', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Role mismatch'),
    ('ScoringReason', 'conflicting_novelty', 'human'): QT_TRANSLATE_NOOP('ScoringReason.human', 'Conflicting novelty'),
    ('ScoringAdjustment', 'correlated_superseded', 'human'): QT_TRANSLATE_NOOP('ScoringAdjustment.human', 'Correlated superseded'),
    ('ScoringAdjustment', 'family_cap', 'human'): QT_TRANSLATE_NOOP('ScoringAdjustment.human', 'Family cap'),
    ('ScoringAdjustment', 'score_cap', 'human'): QT_TRANSLATE_NOOP('ScoringAdjustment.human', 'Score cap'),
    ('ScoringAdjustment', 'mitigation_cap', 'human'): QT_TRANSLATE_NOOP('ScoringAdjustment.human', 'Mitigation cap'),
    ('AssessmentAvailability', 'available', 'human'): QT_TRANSLATE_NOOP('AssessmentAvailability.human', 'Available'),
    ('AssessmentAvailability', 'partial', 'human'): QT_TRANSLATE_NOOP('AssessmentAvailability.human', 'Partial'),
    ('AssessmentAvailability', 'unknown', 'human'): QT_TRANSLATE_NOOP('AssessmentAvailability.human', 'Unknown'),
    ('RiskSeverity', 'info', 'raw'): QT_TRANSLATE_NOOP('RiskSeverity.raw', 'info'),
    ('RiskSeverity', 'info', 'title'): QT_TRANSLATE_NOOP('RiskSeverity.title', 'Info'),
    ('RiskSeverity', 'low', 'raw'): QT_TRANSLATE_NOOP('RiskSeverity.raw', 'low'),
    ('RiskSeverity', 'low', 'title'): QT_TRANSLATE_NOOP('RiskSeverity.title', 'Low'),
    ('RiskSeverity', 'medium', 'raw'): QT_TRANSLATE_NOOP('RiskSeverity.raw', 'medium'),
    ('RiskSeverity', 'medium', 'title'): QT_TRANSLATE_NOOP('RiskSeverity.title', 'Medium'),
    ('RiskSeverity', 'high', 'raw'): QT_TRANSLATE_NOOP('RiskSeverity.raw', 'high'),
    ('RiskSeverity', 'high', 'title'): QT_TRANSLATE_NOOP('RiskSeverity.title', 'High'),
    ('SeverityCapReason', 'reduced_measurement', 'human'): QT_TRANSLATE_NOOP('SeverityCapReason.human', 'Reduced measurement'),
    ('SeverityCapReason', 'unavailable_measurement', 'human'): QT_TRANSLATE_NOOP('SeverityCapReason.human', 'Unavailable measurement'),
    ('SeverityCapReason', 'insufficient_confidence', 'human'): QT_TRANSLATE_NOOP('SeverityCapReason.human', 'Insufficient confidence'),
    ('MaintenanceStatus', 'complete', 'raw'): QT_TRANSLATE_NOOP('MaintenanceStatus.raw', 'complete'),
    ('MaintenanceStatus', 'budget reached; eligible rows may remain', 'raw'): QT_TRANSLATE_NOOP('MaintenanceStatus.raw', 'budget reached; eligible rows may remain'),
    ('MaintenanceStatus', 'cancelled; earlier chunks remain committed', 'raw'): QT_TRANSLATE_NOOP('MaintenanceStatus.raw', 'cancelled; earlier chunks remain committed'),
    ('MaintenanceStatus', 'partial; storage busy or unavailable', 'raw'): QT_TRANSLATE_NOOP('MaintenanceStatus.raw', 'partial; storage busy or unavailable'),
    ('MaintenanceStatus', 'capacity pressure; protected data remains', 'raw'): QT_TRANSLATE_NOOP('MaintenanceStatus.raw', 'capacity pressure; protected data remains'),
    ('SuppressionDisposition', 'not_applicable', 'human'): QT_TRANSLATE_NOOP('SuppressionDisposition.human', 'Not applicable'),
    ('SuppressionDisposition', 'not_suppressed', 'human'): QT_TRANSLATE_NOOP('SuppressionDisposition.human', 'Not suppressed'),
    ('SuppressionDisposition', 'suppressed', 'human'): QT_TRANSLATE_NOOP('SuppressionDisposition.human', 'Suppressed'),
    ('SuppressionDisposition', 'partially_suppressed', 'human'): QT_TRANSLATE_NOOP('SuppressionDisposition.human', 'Partially suppressed'),
    ('SuppressionDisposition', 'indeterminate', 'human'): QT_TRANSLATE_NOOP('SuppressionDisposition.human', 'Indeterminate'),
    ('SuppressionDisposition', 'unavailable', 'human'): QT_TRANSLATE_NOOP('SuppressionDisposition.human', 'Unavailable'),
    ('SuppressionLimitation', 'candidates_truncated', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Candidates truncated'),
    ('SuppressionLimitation', 'matches_truncated', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Matches truncated'),
    ('SuppressionLimitation', 'corrupt_preference', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Corrupt preference'),
    ('SuppressionLimitation', 'unsupported_preference_format', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Unsupported preference format'),
    ('SuppressionLimitation', 'lookup_unavailable', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Lookup unavailable'),
    ('SuppressionLimitation', 'evaluation_unavailable', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Evaluation unavailable'),
    ('SuppressionLimitation', 'evaluator_not_configured', 'human'): QT_TRANSLATE_NOOP('SuppressionLimitation.human', 'Evaluator not configured'),
    ('ThreatIntelResultStatus', 'hit', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelResultStatus.upper', 'HIT'),
    ('ThreatIntelResultStatus', 'no_hit', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelResultStatus.upper', 'NO_HIT'),
    ('ThreatIntelResultStatus', 'error', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelResultStatus.upper', 'ERROR'),
    ('ThreatIntelError', 'unavailable', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'unavailable'),
    ('ThreatIntelError', 'timeout', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'timeout'),
    ('ThreatIntelError', 'authentication', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'authentication'),
    ('ThreatIntelError', 'rate_limited', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'rate limited'),
    ('ThreatIntelError', 'invalid_response', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'invalid response'),
    ('ThreatIntelError', 'credential_unavailable', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'credential unavailable'),
    ('ThreatIntelError', 'subscription_restricted', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'subscription restricted'),
    ('ThreatIntelError', 'invalid_request', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'invalid request'),
    ('ThreatIntelError', 'unsupported', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'unsupported'),
    ('ThreatIntelError', 'http_error', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'http error'),
    ('ThreatIntelError', 'redirect_rejected', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'redirect rejected'),
    ('ThreatIntelError', 'network_error', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'network error'),
    ('ThreatIntelError', 'transport_security_error', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'transport security error'),
    ('ThreatIntelError', 'response_too_large', 'words'): QT_TRANSLATE_NOOP('ThreatIntelError.words', 'response too large'),
    ('ThreatIntelCacheFreshness', 'miss', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'MISS'),
    ('ThreatIntelCacheFreshness', 'fresh', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'FRESH'),
    ('ThreatIntelCacheFreshness', 'stale', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'STALE'),
    ('ThreatIntelCacheFreshness', 'expired', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'EXPIRED'),
    ('ThreatIntelCacheFreshness', 'corrupt', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'CORRUPT'),
    ('ThreatIntelCacheFreshness', 'unsupported', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'UNSUPPORTED'),
    ('ThreatIntelCacheFreshness', 'unavailable', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'UNAVAILABLE'),
    ('ThreatIntelCacheFreshness', 'clock_anomaly', 'upper'): QT_TRANSLATE_NOOP('ThreatIntelCacheFreshness.upper', 'CLOCK_ANOMALY'),
    ('ThreatIntelEvidenceStatus', 'attached', 'words'): QT_TRANSLATE_NOOP('ThreatIntelEvidenceStatus.words', 'attached'),
    ('ThreatIntelEvidenceStatus', 'no_context', 'words'): QT_TRANSLATE_NOOP('ThreatIntelEvidenceStatus.words', 'no context'),
    ('ThreatIntelEvidenceStatus', 'subject_mismatch', 'words'): QT_TRANSLATE_NOOP('ThreatIntelEvidenceStatus.words', 'subject mismatch'),
    ('ThreatIntelEvidenceStatus', 'unsupported', 'words'): QT_TRANSLATE_NOOP('ThreatIntelEvidenceStatus.words', 'unsupported'),
    ('EngineState', 'stopped', 'raw'): QT_TRANSLATE_NOOP('EngineState.raw', 'stopped'),
    ('EngineState', 'stopped', 'human'): QT_TRANSLATE_NOOP('EngineState.human', 'Stopped'),
    ('EngineState', 'running', 'raw'): QT_TRANSLATE_NOOP('EngineState.raw', 'running'),
    ('EngineState', 'running', 'human'): QT_TRANSLATE_NOOP('EngineState.human', 'Running'),
    ('EngineState', 'stopping', 'raw'): QT_TRANSLATE_NOOP('EngineState.raw', 'stopping'),
    ('EngineState', 'stopping', 'human'): QT_TRANSLATE_NOOP('EngineState.human', 'Stopping'),
    ('PersistenceState', 'stopped', 'raw'): QT_TRANSLATE_NOOP('PersistenceState.raw', 'stopped'),
    ('PersistenceState', 'running', 'raw'): QT_TRANSLATE_NOOP('PersistenceState.raw', 'running'),
    ('PersistenceState', 'stopping', 'raw'): QT_TRANSLATE_NOOP('PersistenceState.raw', 'stopping'),
    ('CaptureState', 'stopped', 'raw'): QT_TRANSLATE_NOOP('CaptureState.raw', 'stopped'),
    ('CaptureState', 'stopped', 'human'): QT_TRANSLATE_NOOP('CaptureState.human', 'Stopped'),
    ('CaptureState', 'starting', 'raw'): QT_TRANSLATE_NOOP('CaptureState.raw', 'starting'),
    ('CaptureState', 'starting', 'human'): QT_TRANSLATE_NOOP('CaptureState.human', 'Starting'),
    ('CaptureState', 'running', 'raw'): QT_TRANSLATE_NOOP('CaptureState.raw', 'running'),
    ('CaptureState', 'running', 'human'): QT_TRANSLATE_NOOP('CaptureState.human', 'Running'),
    ('CaptureState', 'stopping', 'raw'): QT_TRANSLATE_NOOP('CaptureState.raw', 'stopping'),
    ('CaptureState', 'stopping', 'human'): QT_TRANSLATE_NOOP('CaptureState.human', 'Stopping'),
    ('CapabilityStatus', 'available', 'human'): QT_TRANSLATE_NOOP('CapabilityStatus.human', 'Available'),
    ('CapabilityStatus', 'available', 'raw'): QT_TRANSLATE_NOOP('CapabilityStatus.raw', 'available'),
    ('CapabilityStatus', 'degraded', 'human'): QT_TRANSLATE_NOOP('CapabilityStatus.human', 'Degraded'),
    ('CapabilityStatus', 'degraded', 'raw'): QT_TRANSLATE_NOOP('CapabilityStatus.raw', 'degraded'),
    ('CapabilityStatus', 'unavailable', 'human'): QT_TRANSLATE_NOOP('CapabilityStatus.human', 'Unavailable'),
    ('CapabilityStatus', 'unavailable', 'raw'): QT_TRANSLATE_NOOP('CapabilityStatus.raw', 'unavailable'),
    ('DatabaseStatus', 'available', 'human'): QT_TRANSLATE_NOOP('DatabaseStatus.human', 'Available'),
    ('DatabaseStatus', 'available', 'raw'): QT_TRANSLATE_NOOP('DatabaseStatus.raw', 'available'),
    ('DatabaseStatus', 'unavailable', 'human'): QT_TRANSLATE_NOOP('DatabaseStatus.human', 'Unavailable'),
    ('DatabaseStatus', 'unavailable', 'raw'): QT_TRANSLATE_NOOP('DatabaseStatus.raw', 'unavailable'),
    ('DatabaseStatus', 'not_checked', 'human'): QT_TRANSLATE_NOOP('DatabaseStatus.human', 'Not checked'),
    ('DatabaseStatus', 'not_checked', 'raw'): QT_TRANSLATE_NOOP('DatabaseStatus.raw', 'not_checked'),
    ('TimelineKind', 'Observation', 'raw'): QT_TRANSLATE_NOOP('TimelineKind.raw', 'Observation'),
    ('TimelineKind', 'Inference / correlation', 'raw'): QT_TRANSLATE_NOOP('TimelineKind.raw', 'Inference / correlation'),
    ('TimelineKind', 'Assessment', 'raw'): QT_TRANSLATE_NOOP('TimelineKind.raw', 'Assessment'),
    ('TimelineKind', 'User action / lifecycle', 'raw'): QT_TRANSLATE_NOOP('TimelineKind.raw', 'User action / lifecycle'),
    ('SubmissionState', 'accepted', 'words'): QT_TRANSLATE_NOOP('SubmissionState.words', 'accepted'),
    ('SubmissionState', 'coalesced', 'words'): QT_TRANSLATE_NOOP('SubmissionState.words', 'coalesced'),
    ('SubmissionState', 'rejected_policy', 'words'): QT_TRANSLATE_NOOP('SubmissionState.words', 'rejected policy'),
    ('SubmissionState', 'capacity_reached', 'words'): QT_TRANSLATE_NOOP('SubmissionState.words', 'capacity reached'),
    ('SubmissionState', 'stopped', 'words'): QT_TRANSLATE_NOOP('SubmissionState.words', 'stopped'),
    ('SubmissionState', 'invalid', 'words'): QT_TRANSLATE_NOOP('SubmissionState.words', 'invalid'),
    ('LookupState', 'queued', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'queued'),
    ('LookupState', 'in_flight', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'in flight'),
    ('LookupState', 'delayed', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'delayed'),
    ('LookupState', 'offline_deferred', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'offline deferred'),
    ('LookupState', 'fresh_cache', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'fresh cache'),
    ('LookupState', 'provider_result', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'provider result'),
    ('LookupState', 'provider_error', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'provider error'),
    ('LookupState', 'cancelled_consent', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'cancelled consent'),
    ('LookupState', 'cancelled_shutdown', 'words'): QT_TRANSLATE_NOOP('LookupState.words', 'cancelled shutdown'),
}

def enum_source(value: Enum, style: str = "raw") -> str:
    source = _SOURCES.get((type(value).__name__, value.value, style))
    if source is not None:
        return source
    # Unknown codes retain the previous canonical display, never identity mutation.
    label = str(value.value) if style in ("raw", "upper") else str(value.value).replace("_", " ")
    if style == "title":
        return label.title()
    if style == "human":
        return label.capitalize()
    if style == "upper":
        return label.upper()
    return label
